apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-datasources
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        url: {{ .Values.datasources.lokiUrl }}
        access: proxy
        isDefault: false
      - name: Prometheus
        type: prometheus
        uid: Prometheus
        url: {{ .Values.datasources.prometheusUrl }}
        access: proxy
        isDefault: true
