# helm/charts/ai-server/templates/configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  namespace: {{ .Values.namespace }}

data:
  APP_ENV: {{ .Values.config.appEnv | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  LOG_DIR: {{ .Values.config.logDir | quote }}
  LOG_FILE_NAME: {{ .Values.config.logFileName | quote }}
  METRICS_ENABLED: {{ .Values.config.metricsEnabled | quote }}
  HOST: {{ .Values.config.host | quote }}
  PORT: {{ .Values.config.port | quote }}
  CALLBACK_URL: {{ .Values.config.callbackUrl | quote }}
  EXERCISE_API_URL: {{ .Values.config.exerciseApiUrl | quote }}
  QDRANT_URL: {{ .Values.config.qdrantUrl | quote }}