apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  clusterIP: None  # Headless Service
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: http
      port: 12345
      targetPort: 12345
