# helm/charts/backend/templates/configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  namespace: {{ .Values.namespace }}

data:
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfile | quote }}

  # AI 서버 연동
  AI_SERVER_ROUTINE_API: {{ .Values.config.aiServerRoutineApi | quote }}
  AI_SERVER_ROUTINE_ASYNC_API: {{ .Values.config.aiServerRoutineAsyncApi | quote }}
  AI_SERVER_USER_PROFILE_API: {{ .Values.config.aiServerUserProfileApi | quote }}
  AI_SERVER_SATISFACTION_API: {{ .Values.config.aiServerSatisfactionApi | quote }}

  # AWS S3
  STORAGE_PROVIDER: {{ .Values.config.storageProvider | quote }}
  AWS_REGION: {{ .Values.config.awsRegion | quote }}
  ICON_URL: {{ .Values.config.iconUrl | quote }}