events {
    worker_connections 1024;
}

http {
    upstream frontend_nextjs {
        server frontend:3000; # 도커 네트워크 내부이므로 컨테이너 이름 사용
        keepalive 32;
    }

    upstream backend_spring {
        server backend:8080; # 컨테이너 이름 사용
        keepalive 32;
    }

    server {
        listen 80;
        listen [::]:80;
        server_name dev.raisedeveloper.com;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        listen [::]:443 ssl ipv6only=on;
        server_name dev.raisedeveloper.com;

        http2 on;

        # 도커 볼륨으로 연결된 인증서 경로
        ssl_certificate /etc/letsencrypt/live/dev.raisedeveloper.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/dev.raisedeveloper.com/privkey.pem;

        # 보안을 위한 기본 SSL 설정
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;

        client_max_body_size 10M;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location /api/bff {
            proxy_pass http://frontend_nextjs;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $http_x_forwarded_for;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }

        location /api {
            proxy_pass http://backend_spring;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $http_x_forwarded_for;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
            proxy_read_timeout 130s;
            proxy_connect_timeout 130s;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }

        location / {
            proxy_pass http://frontend_nextjs;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $http_x_forwarded_for;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}