# helm/envs/dev/ai-values.yaml
image:
  tag: "dev-f48c73b0b70b7c98ea516c1e7e2f087d7d6bf432"

replicaCount: 1

resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "900m"
    memory: "1.5Gi"

hpa:
  enabled: false

pdb:
  minAvailable: 0

namespace: dev-app

nodeSelector:
  role: dev-worker

toleration: "dev-worker"

config:
  appEnv: "dev"
  metricsEnabled: "true"
  callbackUrl: "https://dev.raisedeveloper.com/api/routines/callback"
  exerciseApiUrl: "https://dev.raisedeveloper.com/api/exercises"
  qdrantUrl: "http://10.1.1.12:6333"