# helm/envs/dev/ai-values.yaml
image:
  tag: "dev-486842dc4148cf0f7e736ae4480a2bcdc6b0e77c"

replicaCount: 1

resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "700m"
    memory: "1024Mi"

hpa:
  enabled: false

pdb:
  minAvailable: 0

namespace: dev-app

nodeSelector:
  role: dev-worker

toleration: "dev-worker"

config:
  appEnv: "dev"
  metricsEnabled: "true"
  callbackUrl: "https://dev.raisedeveloper.com/api/routines/callback"
  exerciseApiUrl: "https://dev.raisedeveloper.com/api/exercises"
  qdrantUrl: "http://10.1.40.234:6333"