apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frontend-secret
  namespace: prod-app
spec:
  encryptedData:
    REDIS_URL: AgBAB3OdsT8Uec4g3kEPyR+uQk1rIhHLzRICVfLuMOr1a3nu9QfI2YrO/QnDSURJxBrpUIqZTyjwe+LqR8L4uVq4FF7d+wcfeKjCoF200IOkhSbAHo3pgPga55PjfcICqVSWmFSjNZXowlQCjhqq68F8DWgY2cLv1uhln4GH0wfvMuOlK4sUNdgBVNFax4+dPy6zaXIfIPpryolRi1Wgd9K1avsBqTKlB/R4cPHOao/P/ERE2BID0rj9ggeInRd+lRr+MUXzE42ydg7pmyPuwoLFUlS/oL0Mh2n9+aL7tAkgscuYMz3ZLNYY7PsvX2Je40xtCajRKyAiTAUFUslIEc4RNUhgBQeLTZ7kF3w2LG2gvie49KVo7CfFbhjQCRqwQlYhb366OM5cPF0KZ4LgH8o4D0BnUilBXdgoRmdMknbbrXDNZvFn6rn7HLhyVhLxNJcvijL/bOgfIaW5yadVghNXwS8QQOpqrG4WLB8qLSMAACBxwHimi/BdNpMM+GQtuLtnH2cTY/UNqvGydRQeksVsr3sST7n8/PfgPIEbsyXr9ACkH8YztO4mhwvfTDdNdJz6UmA5aejNCQoKjrZvilc4+9xq+gQ1uD/yu9fKdbSVrRnR5xxb+YM9z/gj6slTtPLXeZfIf1/7HQm6BFPsdABq3nDGsPaeT678XQniuVUiMgNJl3U5oMk47aIk+aQoSgszC6TP/FUiMHz9ltTRjUjiw4uLk/k6SKo=
  template:
    metadata:
      name: frontend-secret
      namespace: prod-app
    type: Opaque