# argocd/apps/dev-sealed-secrets.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: dev-project

  source:
    repoURL: https://github.com/100-hours-a-week/1-team-one-cloud.git
    targetRevision: HEAD
    path: sealed-secrets/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: dev-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true