# argocd/apps/dev-ccm.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-ccm
  namespace: argocd
spec:
  project: dev-project
  source:
    repoURL: https://kubernetes.github.io/cloud-provider-aws
    chart: aws-cloud-controller-manager
    targetRevision: 1.35.0 # 최근 안정 버전 권장
    helm:
      values: |
        args:
          - --v=2
          - --cloud-provider=aws
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system # CCM은 kube-system에 위치
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
# argocd/apps/dev-envoy-gateway.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-envoy-gateway
  namespace: argocd
spec:
  project: dev-project
  source:
    # Envoy Gateway OCI Chart
    repoURL: docker.io/envoyproxy
    chart: gateway-helm
    targetRevision: v1.37.1
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
# argocd/apps/dev-gateway-config.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-gateway-config
  namespace: argocd
spec:
  project: dev-project
  source:
    repoURL: https://github.com/100-hours-a-week/1-team-one-cloud.git
    targetRevision: HEAD
    path: kubernetes/gateway/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
