# argocd/apps/dev-backend.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: dev-project

  source:
    repoURL: https://github.com/100-hours-a-week/1-team-one-cloud.git
    targetRevision: HEAD
    path: helm/charts/backend
    helm:
      valueFiles:
        - ../../../helm/envs/dev/backend-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dev-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true