apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: prod-project # 공통 인프라이므로 기존 프로젝트 활용
  source:
    repoURL: https://github.com/100-hours-a-week/1-team-one-cloud.git
    targetRevision: HEAD
    path: sealed-secrets/monitoring # 새로운 경로 지정
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
