apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-storage-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: prod-project
  source:
    repoURL: https://github.com/100-hours-a-week/1-team-one-cloud.git
    targetRevision: HEAD
    path: k8s-infra/storage
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
