# argocd/apps/prod-sealed-secrets.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-sealed-secrets
  namespace: argocd
  annotations:
    # 다른 App보다 먼저 Sync (Secret이 먼저 생성되어야 파드가 뜸)
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: prod-project

  source:
    repoURL: https://github.com/100-hours-a-week/1-team-one-cloud.git
    targetRevision: HEAD
    path: sealed-secrets/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: prod-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true