apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frontend-secret
  namespace: dev-app
spec:
  encryptedData:
    REDIS_URL: AgCFA3e+bii1BMk9Gl1Qn6423s8wl4XUrOWrufriR84/pTs0zq1o98zcxrjLWi7uuCQJLSLHtPgOfBDSLf+XO5Z6APgx278ZWR1DXA4OW1Ii/I2gwZH1TNDxV5GOCD6I+Ngl0niF0yx/FL0dyLqcjQ1UK68sSlegpU1eauuOUBrjKzxPrtr8qF2xDWSu/Y/faLT36GcKpMNW1OwCiGjMgYzN2MuwnJj3VrhAG1kPC4jaxzRtcylapiYuHqKsOjeaaOS+9L8+28Zm3cfGcovUew/U6L5cG6J84desKg+TB0pyGHHKszIGXsZMe572vJ5c7r3b0gRPT5xCwo1/QMjqWLb6W001YtVLIcQ5nplU9okdr05Q5n3NDeXLFh5y1kEgnGCVM3+5MfRdRzjBdOtYJSNhU61TO1ldpI90oAzdgL+9NMxS0HT/3t0j9k6tlkyXYpdOPB4PllOKywOg4xJDkzNemksmYU+36mqXT2+SijX+vDnJmBYjQSavcdmb1B4G3W3vMJybCyFQLp7cHdbnnsm4gJFRLpe55jRscYA4lDABlSLDDysPqZij4yjtqFI31JUDrql3/gHfzevAfFjccP+vyPxTkyChkzAln3XVn71xRQZ0PdxEYgEGJrihbQ17EOcrZff+LqtKMFRKvI0QDdQ7ZwKia+903NXVX2gAScpoTTXYussg1Uj067xpFc/JSMTJBC1o8bW9/82cdo3A7oc13Kylh3rX3OeUOX1/VxX3Ew==
  template:
    metadata:
      name: frontend-secret
      namespace: dev-app
    type: Opaque