apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter-rds
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-exporter-rds
  template:
    metadata:
      labels:
        app: mysql-exporter-rds
    spec:
      containers:
        - name: mysql-exporter
          image: prom/mysqld-exporter:latest
          env:
            - name: MYSQLD_EXPORTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: monitoring-secret
                  key: RDS_PASSWORD
          command:
            - "/bin/mysqld_exporter"
            - "--mysqld.address=$(RDS_HOSTNAME):3306"
            - "--mysqld.username=$(RDS_USERNAME)"
          envFrom:
            - secretRef:
                name: monitoring-secret
          ports:
            - containerPort: 9104
              name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter-rds
  namespace: monitoring
spec:
  selector:
    app: mysql-exporter-rds
  ports:
    - protocol: TCP
      port: 9104
      targetPort: 9104
